import {randomUUID} from 'node:crypto'
import {stripeAPI,verificarPagamentoLicenca} from '@/lib/stripe-licenca'
import {NextRequest,NextResponse} from 'next/server'
import {adminSistema} from '@/lib/admin-sistema'
import {servicoAuditado} from '@/lib/supabase/servico-auditado'
import {diasLicenca,estadoLicenca,validarAntecedencias,linkLicenca} from '@/lib/licenca'
export const dynamic='force-dynamic'
const json=(body:unknown,status=200)=>NextResponse.json(body,{status,headers:{'Cache-Control':'no-store'}})
export async function GET(){const a=await adminSistema();if(!a.user)return json({error:'Acesso restrito'},a.status);const db=servicoAuditado(a.user.id);const {error:geracao}=await db.rpc('licenca_gerar_avisos');if(geracao)return json({error:'Avisos de licença ainda não configurados no banco'},503);const {data:l,error}=await db.from('licenca_sistema').select('id,empresa,data_vencimento,renovar_url,assinatura_url').eq('instalacao',true).maybeSingle();const {data:config,error:erroConfig}=await db.from('licenca_avisos_config').select('*').eq('id',true).single();if(error||erroConfig)return json({error:'Não foi possível consultar a licença'},503);if(!l)return json({licenca:null,config});if(!l.data_vencimento)return json({licenca:l,config,dias:null,status:'PENDENTE',aviso:null});const dias=diasLicenca(l.data_vencimento);const {data:aviso,error:erroAviso}=await db.from('licenca_avisos').select('id,data_vencimento').eq('license_id',l.id).eq('data_vencimento',l.data_vencimento).is('cancelado_em',null).eq('canal_da_notificacao','interno').eq('status','enviado').order('data_hora_envio',{ascending:false}).limit(1).maybeSingle();if(erroAviso)return json({error:'Não foi possível consultar os avisos'},503);return json({licenca:{...l,renovar_url:linkLicenca(l.renovar_url),assinatura_url:linkLicenca(l.assinatura_url)},config,dias,status:dias===null?'PENDENTE':estadoLicenca(dias),aviso:config.interno&&dias!==null&&dias>=0?aviso:null,pagamento_configurado:true})}
export async function PUT(req:NextRequest){const a=await adminSistema();if(!a.user)return json({error:'Acesso restrito'},a.status);try{const body=await req.json();const antecedencias=validarAntecedencias(body.antecedencias);if(typeof body.interno!=='boolean'||typeof body.versao!=='string')throw Error();const {error}=await servicoAuditado(a.user.id).from('licenca_avisos_config').update({antecedencias,interno:body.interno,atualizado_em:new Date().toISOString()}).eq('id',true).eq('atualizado_em',body.versao).select('id').single();return error?json({error:'Configuração alterada. Recarregue e tente novamente.'},409):json({sucesso:true})}catch{return json({error:'Antecedências inválidas. Use números inteiros entre 0 e 365.'},400)}}

export async function POST(req:NextRequest){const a=await adminSistema();if(!a.user)return json({error:'Acesso restrito'},a.status);const db=servicoAuditado(a.user.id);try{const {acao}=await req.json();if(!['renovar','assinatura','verificar'].includes(acao))return json({error:'Ação inválida'},400);const {data:c,error:ec}=await db.from('licenca_integracoes').select('*').eq('id',true).single();if(ec||!c.stripe_secret||!c.stripe_price||!c.empresa)return json({error:'Configure o Stripe em Configurações → Licença e assinatura.'},503);let {data:l,error:el}=await db.from('licenca_sistema').select('*').eq('instalacao',true).maybeSingle();if(el)throw Error();if(!l){const {error}=await db.from('licenca_sistema').insert({id:randomUUID(),empresa:c.empresa});if(error&&error.code!=='23505')throw Error();const novo=await db.from('licenca_sistema').select('*').eq('instalacao',true).single();l=novo.data;if(!l)throw Error()}
 const retorno=c.app_url+'/dashboard/configuracoes';
 if(acao==='verificar')return json(await verificarPagamentoLicenca(db,c,l));
 if(l.stripe_customer_id){const portal=await stripeAPI(c.stripe_secret,'billing_portal/sessions',{customer:l.stripe_customer_id,return_url:retorno});return json({url:portal.url})}
 if(acao==='assinatura')return json({error:'Nenhuma assinatura vinculada. Use Renovar agora para iniciar a assinatura.'},409);
 if(l.checkout_session_id){const existente=await stripeAPI(c.stripe_secret,'checkout/sessions/'+encodeURIComponent(l.checkout_session_id));if(existente.status==='open'&&existente.url)return json({url:existente.url});if(existente.subscription)return json({error:'Checkout concluído. Clique em Verificar pagamento.'},409)}
 const sessao=await stripeAPI(c.stripe_secret,'checkout/sessions',{'mode':'subscription','line_items[0][price]':c.stripe_price,'line_items[0][quantity]':'1','client_reference_id':l.id,'metadata[license_id]':l.id,'subscription_data[metadata][license_id]':l.id,'success_url':retorno+'?licenca=pagamento','cancel_url':retorno+'?licenca=cancelado'},'license-checkout-'+l.id+'-'+new Date().toISOString().slice(0,10));
 const {error}=await db.from('licenca_sistema').update({checkout_session_id:sessao.id}).eq('id',l.id);if(error)throw Error();return json({url:sessao.url});
 }catch{return json({error:'Não foi possível concluir a operação no Stripe. Confira a integração e tente novamente.'},502)}}
