import {NextRequest,NextResponse} from 'next/server'
import {adminSistema} from '@/lib/admin-sistema'
import {servicoAuditado} from '@/lib/supabase/servico-auditado'
import {z} from 'zod'
export const dynamic='force-dynamic'
const schema=z.object({empresa:z.string().trim().min(1).max(160),app_url:z.string().url().refine(v=>{const u=new URL(v);return !u.username&&!u.password&&!u.search&&!u.hash&&u.pathname==='/'&&(u.protocol==='https:'||(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))}),stripe_price:z.string().regex(/^price_[A-Za-z0-9]+$/),stripe_secret:z.string().max(250).optional(),stripe_webhook:z.string().max(250).optional(),resend_key:z.string().max(250).optional(),email_ativo:z.boolean(),email_destino:z.string().max(200),email_remetente:z.string().max(200),whatsapp_ativo:z.boolean(),whatsapp_provider:z.string().uuid().nullable(),whatsapp_destino:z.string().max(20),whatsapp_template:z.string().max(100),versao:z.string()})
export async function GET(){const a=await adminSistema();if(!a.user)return NextResponse.json({error:'Acesso restrito'},{status:a.status});const db=servicoAuditado(a.user.id);const {data,error}=await db.from('licenca_integracoes').select('*').eq('id',true).single();if(error)return NextResponse.json({error:'Aplique a migração da integração Stripe'},{status:503});const {stripe_secret,stripe_webhook,resend_key,...seguro}=data;const {data:providers}=await db.from('whatsapp_providers').select('id,nome,tipo').eq('ativo',true);return NextResponse.json({...seguro,stripe_configurado:!!stripe_secret,webhook_configurado:!!stripe_webhook,email_configurado:!!resend_key,providers:providers||[]},{headers:{'Cache-Control':'no-store'}})}
export async function PUT(req:NextRequest){const a=await adminSistema();if(!a.user)return NextResponse.json({error:'Acesso restrito'},{status:a.status});try{const b=schema.parse(await req.json());const db=servicoAuditado(a.user.id);const {data:atual,error:consulta}=await db.from('licenca_integracoes').select('*').eq('id',true).single();if(consulta)throw Error();const {versao,...input}=b;const payload:any={...input,app_url:b.app_url.replace(/\/$/,''),atualizado_em:new Date().toISOString()};for(const k of ['stripe_secret','stripe_webhook','resend_key'] as const){if(!b[k])delete payload[k]}
 if(payload.stripe_secret&&!/^sk_(test|live)_[A-Za-z0-9]+$/.test(payload.stripe_secret))throw Error();if(payload.stripe_webhook&&!/^whsec_[A-Za-z0-9]+$/.test(payload.stripe_webhook))throw Error();
 if(b.email_ativo&&(!z.string().email().safeParse(b.email_destino).success||!z.string().email().safeParse(b.email_remetente).success||!(payload.resend_key||atual.resend_key)))throw Error();
 if(b.whatsapp_ativo){if(!b.whatsapp_provider||!/^\+?[1-9]\d{9,14}$/.test(b.whatsapp_destino))throw Error();const {data:p}=await db.from('whatsapp_providers').select('tipo').eq('id',b.whatsapp_provider).eq('ativo',true).single();if(!p||(p.tipo==='meta'&&!/^[a-z0-9_]+$/.test(b.whatsapp_template)))throw Error()}
 const {error}=await db.from('licenca_integracoes').update(payload).eq('id',true).eq('atualizado_em',versao).select('id').single();if(error)return NextResponse.json({error:'Configuração alterada. Recarregue antes de salvar.'},{status:409});return NextResponse.json({sucesso:true})}catch{return NextResponse.json({error:'Confira empresa, URL, preço do Stripe, chaves e os canais habilitados.'},{status:400})}}
