'use client'
import {AvisosAssociado} from '@/components/avisos/AvisosAssociado'
import {RodapeDesenvolvedor} from '@/components/RodapeDesenvolvedor'
import {IconeClube} from '@/components/providers/tema-provider'
import {useEffect,useState} from 'react'
import {QrCode,Receipt,HeartPulse,MessageSquare,LogOut,RefreshCw,ArrowRight,ShieldCheck,ChevronLeft,Eye,EyeOff} from 'lucide-react'
import './portal.css'
import {MensagensClube} from '@/components/MensagensClube'
import {AvisoMensagens} from '@/components/AvisoMensagens'
import {desligarPush} from '@/components/NotificacoesClube'
import {ErroPortal,mensagemPortal,portalApi} from '@/lib/portal-api'
import {EVENTO_SESSAO} from '@/lib/mensagens-eventos'
const date=(v:string)=>v?new Date(v.slice(0,10)+'T12:00:00').toLocaleDateString('pt-BR'):'Não informado'
const uuid=()=> '10000000-1000-4000-8000-100000000000'.replace(/[018]/g,c=>(Number(c)^(crypto.getRandomValues(new Uint8Array(1))[0]&15)>>Number(c)/4).toString(16))
const money=(v:any)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const formatarCpfLogin=(v:string)=>v.replace(/\D/g,'').slice(0,11).replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/^(\d{3})\.(\d{3})\.(\d{3})(\d)/,'$1.$2.$3-$4')
export default function AssociadoApp(){
 const [data,setData]=useState<any>(null),[screen,setScreen]=useState('loading'),[tab,setTab]=useState('inicio'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[cpf,setCpf]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[showPassword,setShowPassword]=useState(false),[page,setPage]=useState(0),[filter,setFilter]=useState('todas'),[form,setForm]=useState({id:'',assunto:'',descricao:'',local:'',data_ocorrencia:''});
 async function api(path:string,body?:any){return portalApi('/api/associado-app'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{},{login:body?.acao==='entrar'})}
 async function load(p=page){setBusy(true);setError('');try{const j=await api('?pagina='+p);if(j.trocar_senha){setScreen('senha');return}if(!j.associado||typeof j.associado.nome!=='string'||!Array.isArray(j.mensalidades)||!Array.isArray(j.exames)||!Array.isArray(j.relatos))throw new ErroPortal('Não foi possível carregar as informações. Tente novamente.');setData(j);setPage(p);setScreen('app')}catch(e:any){if(e.status===401){setData(null);setScreen('login')}else{setError(mensagemPortal(e));setScreen(s=>s==='loading'?'login':s)}}finally{setBusy(false)}}
 useEffect(()=>{const expirada=()=>{setData(null);setScreen('login');setError('Sua sessão expirou. Entre novamente.')};window.addEventListener(EVENTO_SESSAO,expirada);return()=>window.removeEventListener(EVENTO_SESSAO,expirada)},[])
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('aba')==='mensagens')setTab('mensagens');load(0)},[])
 async function auth(acao:string){setBusy(true);setError('');setNotice('');try{if(acao==='sair'){try{await desligarPush('associado')}catch{}}if(acao==='senha'&&password!==confirm)throw new ErroPortal('As senhas precisam ser iguais.');const j=await api('/auth',{acao,cpf,senha:password});setPassword('');setConfirm('');if(acao==='enviar')setNotice('Se o CPF possuir cadastro e e-mail, enviaremos uma senha temporária. Confira sua caixa de entrada.');else if(acao==='sair'){setData(null);setScreen('login');setTab('inicio')}else if(j.trocar_senha)setScreen('senha');else await load(0)}catch(e:any){setError(mensagemPortal(e))}finally{setBusy(false)}}
 async function send(){setBusy(true);setError('');try{const id=form.id||uuid();setForm(f=>({...f,id}));const j=await api('',{...form,id});setNotice('Relato recebido. Protocolo '+j.id.slice(0,8).toUpperCase());setForm({id:'',assunto:'',descricao:'',local:'',data_ocorrencia:''});setTab('relatos');await load()}catch(e:any){setError(mensagemPortal(e))}finally{setBusy(false)}}
 const titulos:Record<string,string>={inicio:'Sua carteirinha',mensalidades:'Mensalidades',exames:'Exames médicos',relatos:'Meus relatos',novo:'Novo relato',mensagens:'Mensagens'};
 const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});
 const status=(m:any)=>m.status==='pago'?'Pago':m.status==='cancelado'?'Cancelado':m.data_vencimento<today?'Vencido':'A vencer';
 return <main className="socio-app" aria-busy={busy}>
 <header className="socio-header"><a href="/associado" className="socio-brand"><IconeClube className="h-8 w-8"/><span>CLUBE<span>Área do associado</span></span></a>{screen==='app'&&<div className="socio-header-actions"><AvisoMensagens tipo="associado" onClick={()=>{setTab('mensagens');setError('')}}/><button aria-label="Sair do aplicativo" onClick={()=>auth('sair')} disabled={busy}><LogOut size={21}/></button></div>}</header>
 <div className="socio-content">
 {error&&<div role="alert" className="socio-alert">{error}</div>}{notice&&<div role="status" className="socio-notice">{notice}<button aria-label="Fechar mensagem" onClick={()=>setNotice('')}>×</button></div>}
 {screen==='loading'?<p role="status">Carregando seu acesso…</p>:screen!=='app'?<>
 <div className="socio-intro"><span className="socio-eyebrow">SEU CLUBE, MAIS PERTO</span><h1>{screen==='senha'?'Um acesso só seu.':'Tudo pronto para o seu próximo encontro.'}</h1><p>{screen==='senha'?'Crie sua senha pessoal para continuar. A senha temporária deixará de funcionar.':'Sua carteirinha, mensalidades e informações do clube em um só lugar.'}</p></div>
 <form className="socio-card" onSubmit={e=>{e.preventDefault();auth(screen==='senha'?'senha':'entrar')}}>
 <h2>{screen==='senha'?'Definir minha senha':'Entrar no aplicativo'}</h2>
 {screen!=='senha'&&<label>CPF<input required inputMode="numeric" autoComplete="username" value={formatarCpfLogin(cpf)} onChange={e=>setCpf(e.target.value.replace(/\D/g,'').slice(0,11))} placeholder="000.000.000-00" maxLength={14}/></label>}
 <label>{screen==='senha'?'Nova senha':'Senha'}<span className="socio-password-field"><input required type={showPassword?'text':'password'} autoComplete={screen==='senha'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} minLength={screen==='senha'?10:1} maxLength={128}/><button type="button" className="socio-password-toggle" aria-label={showPassword?'Ocultar senha':'Mostrar senha'} onClick={()=>setShowPassword(v=>!v)}>{showPassword?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>
 {screen==='senha'&&<label>Repita a nova senha<input required type="password" autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={10}/><small>Pelo menos 10 caracteres.</small></label>}
 <button className="socio-primary" disabled={busy}>{busy?'Aguarde…':screen==='senha'?'Salvar e acessar':'Entrar'}<ArrowRight size={18}/></button>
 {screen!=='senha'&&<button type="button" className="socio-link" disabled={busy||cpf.length!==11} onClick={()=>auth('enviar')}>Primeiro acesso ou esqueci minha senha</button>}
 <p className="socio-help">A senha temporária é enviada somente ao e-mail cadastrado no clube. Para atualizar seu e-mail, procure a secretaria.</p></form>
 </>:<>
 <AvisosAssociado/>
 <div className="socio-welcome"><div><span className="socio-eyebrow">Área do associado</span><h1>{tab==='inicio'?<>Olá, {data.associado.nome.split(' ')[0]}.</>:titulos[tab]}</h1></div><button aria-label="Atualizar informações" onClick={()=>load()} disabled={busy}><RefreshCw size={20}/></button></div>
 {tab==='inicio'&&<><section className="socio-pass"><div className="socio-pass-head"><span>Carteirinha digital</span><span className="socio-badge">{data.associado.status}</span></div><div className="socio-qr"><img src={data.qr} alt="QR Code da carteirinha para leitura na portaria" width={240} height={240}/></div><h2>{data.associado.nome}</h2><p>Título {data.associado.numero_titulo}</p><div className="socio-pass-footer"><QrCode size={18}/>Apresente na portaria do clube</div></section><p className="socio-help">A liberação é confirmada na portaria conforme as regras do clube. O QR Code identifica sua carteirinha.</p><div className="socio-shortcuts"><button onClick={()=>setTab('mensalidades')}><Receipt/><strong>Mensalidades</strong><span>Consulte seus pagamentos</span></button><button onClick={()=>setTab('exames')}><HeartPulse/><strong>Exame médico</strong><span>Confira a validade</span></button></div><button className="socio-card socio-incident" onClick={()=>setTab('novo')}><MessageSquare/><span><strong>Precisa relatar uma ocorrência?</strong><small>Envie seu relato para análise do clube.</small></span><ArrowRight size={18}/></button></>}
 {tab==='mensagens'&&<MensagensClube tipo="associado"/>}
 {tab==='mensalidades'&&<section><h2>Minhas mensalidades</h2><p className="socio-help">Valores e pagamentos registrados pelo clube.</p><select aria-label="Filtrar mensalidades" value={filter} onChange={e=>setFilter(e.target.value)}><option value="todas">Todas nesta página</option><option>Pago</option><option>A vencer</option><option>Vencido</option></select>{data.mensalidades.filter((m:any)=>filter==='todas'||status(m)===filter).map((m:any)=><article className="socio-card" key={m.id}><div className="socio-row"><h3>{m.tipo==='academia'?'Academia':'Clube'} · {m.referencia||m.mes_referencia}</h3><span className={'socio-tag '+(status(m)==='Vencido'?'late':'')}>{status(m)}</span></div><strong className="socio-amount">{money(m.valor)}</strong><p>Vencimento: {date(m.data_vencimento)}</p>{m.data_pagamento&&<p>Pago em {date(m.data_pagamento)} · {money(m.valor_pago??m.valor)}</p>}</article>)}{!data.mensalidades.length&&<p className="socio-card">Nenhuma mensalidade cadastrada.</p>}<div className="socio-row"><button disabled={busy||page===0} onClick={()=>load(page-1)}>Anterior</button><small>Página {page+1} · {data.total_mensalidades} registros</small><button disabled={busy||(page+1)*30>=data.total_mensalidades} onClick={()=>load(page+1)}>Próxima</button></div></section>}
 {tab==='exames'&&<section><h2>Meus exames médicos</h2><p className="socio-help">Consulte os últimos exames e programe sua renovação com o clube.</p>{!data.exames.length&&<p className="socio-card">Nenhum exame informado. Procure o atendimento do clube.</p>}{data.exames.map((e:any)=><article className="socio-card" key={e.id}><div className="socio-row"><h3>{e.tipo_exame}</h3><HeartPulse size={22}/></div><p>Resultado: <strong>{e.resultado||e.status||'Não informado'}</strong></p><p>Realizado em {date(e.data_exame)}</p><div className={'socio-expiry '+(e.data_validade<today?'late':'')}>{e.data_validade?(e.data_validade<today?'Vencido desde ':'Validade até ')+date(e.data_validade):'Validade não informada'}</div><small>{e.medico_nome||e.medico}</small></article>)}</section>}
 {tab==='relatos'&&<section><div className="socio-row"><h2>Meus relatos</h2><button onClick={()=>{setNotice('');setTab('novo')}}>Novo relato +</button></div><p className="socio-help">Acompanhe a análise das ocorrências que você informou. Últimos 100 registros.</p>{!data.relatos.length&&<p className="socio-card">Você ainda não enviou nenhum relato.</p>}{data.relatos.map((r:any)=><article className="socio-card" key={r.id}><span className="socio-eyebrow">PROTOCOLO {r.id.slice(0,8).toUpperCase()} · {r.status.replace('_',' ')}</span><h3>{r.assunto}</h3><p>{date(r.data_ocorrencia)} · {r.local}</p><p className="socio-text">{r.descricao}</p>{r.resposta&&<div className="socio-reply"><strong>Resposta do clube</strong><p className="socio-text">{r.resposta}</p></div>}</article>)}</section>}
 {tab==='novo'&&<section><button className="socio-link" onClick={()=>setTab('relatos')}><ChevronLeft size={17}/>Meus relatos</button><h2>Relatar uma ocorrência</h2><p className="socio-help">Conte o que aconteceu com você. A equipe avaliará os fatos antes de qualquer medida.</p><form className="socio-card" onSubmit={e=>{e.preventDefault();send()}}><label>Assunto<input required minLength={3} maxLength={120} value={form.assunto} onChange={e=>setForm({...form,assunto:e.target.value})}/></label><label>Data da ocorrência<input required type="date" max={today} value={form.data_ocorrencia} onChange={e=>setForm({...form,data_ocorrencia:e.target.value})}/></label><label>Local<input required minLength={2} maxLength={200} value={form.local} onChange={e=>setForm({...form,local:e.target.value})} placeholder="Ex.: piscina, salão social"/></label><label>Descreva o ocorrido<textarea required rows={6} minLength={10} maxLength={5000} value={form.descricao} onChange={e=>setForm({...form,descricao:e.target.value})}/></label><button className="socio-primary" disabled={busy}>{busy?'Enviando…':'Enviar relato'}<ArrowRight size={18}/></button></form></section>}
 </>}
 <RodapeDesenvolvedor/>
 </div>{screen==='app'&&<nav className="socio-nav" aria-label="Menu do associado">{[['inicio','Carteirinha',QrCode],['mensalidades','Mensalidades',Receipt],['exames','Exames',HeartPulse],['relatos','Relatos',MessageSquare]].map(([key,label,Icon]:any)=><button key={key} aria-current={tab===key||key==='relatos'&&tab==='novo'?'page':undefined} className={tab===key||key==='relatos'&&tab==='novo'?'selected':''} onClick={()=>{setTab(key);setError('')}}><Icon size={24} aria-hidden="true"/><span>{label}</span></button>)}</nav>}
 </main>
}
