import {NextRequest,NextResponse} from 'next/server'
import {acessoRota} from '@/lib/supabase/acesso-rota'
import {servicoAuditado} from '@/lib/supabase/servico-auditado'
import {compraUsoSchema,tipoAnexo} from '@/lib/compra-uso-clube'
import {createHash,randomUUID} from 'node:crypto'
export const dynamic='force-dynamic'
export const runtime='nodejs'
async function acesso(acao:string){const a=await acessoRota('compras',acao);if(!a)throw Error('Sessão inválida ou sem permissão para compras');return {db:servicoAuditado(a.user.id),user:a.user}}
export async function GET(req:NextRequest){try{const {db}=await acesso('visualizar');const id=req.nextUrl.searchParams.get('id'),tipo=req.nextUrl.searchParams.get('anexo');if(id&&tipo){if(!['nota','comprovante'].includes(tipo))throw Error('Anexo inválido');const {data,error}=await db.from('compras_uso_clube').select('anexos').eq('id',id).single();if(error||!data?.anexos?.[tipo])throw Error('Anexo não encontrado');const a=data.anexos[tipo];const {data:url,error:falha}=await db.storage.from('compras-uso-clube').createSignedUrl(a.path,60,{download:a.nome});if(falha||!url)throw Error('Não foi possível baixar');return NextResponse.redirect(url.signedUrl)}const {data,error}=await db.from('compras_uso_clube').select('id,dados,valor_total,criado_em,anexos').order('criado_em',{ascending:false}).limit(200);if(error)throw error;return NextResponse.json({compras:data},{headers:{'Cache-Control':'no-store'}})}catch(e:any){return NextResponse.json({error:e.message},{status:400})}}
export async function POST(req:NextRequest){let db:any;const enviados:string[]=[];let chamado=false;try{const a=await acesso('criar');db=a.db;if(Number(req.headers.get('content-length')||0)>22*1024*1024)throw Error('Arquivos muito grandes');const form=await req.formData();const id=String(form.get('id')||'');if(!/^[\da-f]{8}-([\da-f]{4}-){3}[\da-f]{12}$/i.test(id))throw Error('Identificador inválido');const dados=compraUsoSchema.parse(JSON.parse(String(form.get('dados'))));const hoje=new Date().toLocaleDateString('en-CA',{timeZone:'America/Sao_Paulo'});if(dados.data_pagamento>hoje||dados.data_nota>hoje)throw Error('Uma compra já paga não pode ter datas futuras');const anexos:any={};const arquivos:any[]=[];const hash=createHash('sha256').update(JSON.stringify(dados));for(const tipo of ['nota','comprovante']){const file=form.get(tipo);if(file instanceof File&&file.size){if(file.size>10*1024*1024)throw Error('Cada arquivo pode ter até 10 MB');const bytes=Buffer.from(await file.arrayBuffer());const formato=tipoAnexo(bytes);hash.update(tipo).update(bytes);arquivos.push({tipo,bytes,...formato,nome:tipo+'.'+formato.ext})}}const assinatura=hash.digest('hex');const {data:existe}=await db.from('compras_uso_clube').select('id,assinatura,registrado_por').eq('id',id).maybeSingle();if(existe){if(existe.assinatura!==assinatura||existe.registrado_por!==a.user.id)throw Error('Identificador já usado para outros dados');return NextResponse.json({id})}for(const f of arquivos){const path=id+'/'+randomUUID()+'.'+f.ext;const {error}=await db.storage.from('compras-uso-clube').upload(path,f.bytes,{contentType:f.mime,upsert:false});if(error)throw Error('Falha ao guardar o anexo');enviados.push(path);anexos[f.tipo]={path,nome:f.nome}}
 chamado=true;const {data:salvo,error}=await db.rpc('registrar_compra_uso',{p_id:id,p_dados:dados,p_anexos:anexos,p_assinatura:assinatura,p_operador:a.user.id});if(error)throw Error(error.code==='23505'?'Já existe uma compra com esse fornecedor, número e data de nota.':error.message);const {data:registro}=await db.from('compras_uso_clube').select('anexos').eq('id',salvo).single();if(registro){const usados=Object.values(registro.anexos).map((v:any)=>v.path);const extras=enviados.filter(p=>!usados.includes(p));if(extras.length)await db.storage.from('compras-uso-clube').remove(extras)}return NextResponse.json({id:salvo})
 }catch(e:any){if(db&&enviados.length&&!chamado)await db.storage.from('compras-uso-clube').remove(enviados);return NextResponse.json({error:e.message||'Não foi possível registrar. Tente novamente com os mesmos dados.'},{status:400})}}
