'use client'
import {useEffect,useState,useRef} from 'react'
import Link from 'next/link'
import {PaginaProtegida,ComPermissao} from '@/components/ui/permissao'
export default function RelatosAssociados(){
 const [rows,setRows]=useState<any[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[draft,setDraft]=useState<Record<string,{status:string,resposta:string}>>({});
 async function load(){try{const r=await fetch('/api/infracoes/relatos',{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.relatos)}catch(e:any){setError(e.message)}}
 const ancorado=useRef(false)
 useEffect(()=>{load()},[])
 useEffect(()=>{if(ancorado.current||!window.location.hash.startsWith('#relato-'))return;const el=document.getElementById(window.location.hash.slice(1));if(el){el.scrollIntoView({block:'start'});ancorado.current=true}},[rows])
 async function save(id:string){setBusy(true);setError('');try{const r=await fetch('/api/infracoes/relatos',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,...draft[id]})}),j=await r.json();if(!r.ok)throw Error(j.error);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <PaginaProtegida codigoPagina="infracoes"><main className="max-w-5xl mx-auto p-6"><Link href="/dashboard/infracoes">← Infrações</Link><h1 className="text-3xl font-bold my-5">Relatos dos associados</h1><p className="text-gray-600">Ocorrências enviadas pelo aplicativo para análise. Um relato não aplica penalidade ao associado. Últimos 200 registros.</p>{error&&<p role="alert" className="p-4 bg-red-50 text-red-700 my-4">{error}</p>}{!rows.length&&<p className="p-8 my-6 bg-white rounded-xl">Nenhum relato recebido.</p>}{rows.map(r=>{const value=draft[r.id]||{status:r.status,resposta:r.resposta||''};return <article id={`relato-${r.id}`} className="p-6 my-5 bg-white border rounded-xl scroll-mt-28" key={r.id}><div className="text-sm text-gray-500">Protocolo {r.id.slice(0,8).toUpperCase()} · {r.status}</div><h2 className="text-xl font-semibold my-3">{r.assunto}</h2><p>{r.associado?.nome} · Título {r.associado?.numero_titulo}</p><p className="text-sm my-2">{r.data_ocorrencia} · {r.local}</p><p className="whitespace-pre-wrap my-4">{r.descricao}</p><ComPermissao codigoPagina="infracoes" acao="editar"><label className="block">Status<select className="block border p-2 my-2 rounded" value={value.status} onChange={e=>setDraft({...draft,[r.id]:{...value,status:e.target.value}})}>{['recebido','em_analise','respondido','encerrado'].map(s=><option key={s}>{s}</option>)}</select></label><label className="block">Resposta visível ao associado<textarea className="w-full border p-3 rounded my-2" rows={4} maxLength={5000} value={value.resposta} onChange={e=>setDraft({...draft,[r.id]:{...value,resposta:e.target.value}})}/></label><button className="bg-blue-600 text-white px-5 py-2 rounded disabled:opacity-50" disabled={busy||!draft[r.id]||value.resposta.trim().length<3} onClick={()=>save(r.id)}>Salvar resposta</button></ComPermissao>{r.resposta&&<p className="whitespace-pre-wrap mt-4 text-gray-600">Última resposta: {r.resposta}</p>}</article>})}</main></PaginaProtegida>
}
