'use client'
import {useEffect,useState,useRef} from 'react'
import {createClient} from '@/lib/supabase/client'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {useFuncionarios} from '../hooks/useRH'
import {toast} from 'sonner'
const horas=(m:number)=>`${Math.floor(m/60)}h ${m%60}min`
export function BancoHorasTab(){
 const db=createClient();const {funcionarios}=useFuncionarios({status:'ativo'})
 const [func,setFunc]=useState(''),[mes,setMes]=useState(new Date().toISOString().slice(0,7)),[creditos,setCreditos]=useState<any[]>([]),[folgas,setFolgas]=useState<any[]>([]),[busy,setBusy]=useState(false),[data,setData]=useState(new Date().toISOString().slice(0,10)),[quantidade,setQuantidade]=useState(''),[motivo,setMotivo]=useState('');const pedido=useRef<string | undefined>(undefined)
 async function carregar(){if(!func){setCreditos([]);setFolgas([]);return}try{const {data:d,error}=await db.from('rh_banco_creditos').select('*,folha:folha_pagamento(status,referencia)').eq('funcionario_id',func).order('data',{ascending:false}).limit(500);if(error)throw error;setCreditos(d||[]);const ids=(d||[]).map(c=>c.id);if(ids.length){const {data:f,error:ef}=await db.from('rh_banco_folgas').select('*').in('credito_id',ids).order('data',{ascending:false}).limit(500);if(ef)throw ef;setFolgas(f||[])}else setFolgas([])}catch(e:any){toast.error(e.message)}}
 useEffect(()=>{void carregar()},[func])
 async function apurar(){setBusy(true);try{const {error}=await db.rpc('rh_banco_apurar',{p_mes:mes});if(error)throw error;toast.success('Pontos apurados. Créditos existentes não foram duplicados.');await carregar()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function compensar(e:React.FormEvent){e.preventDefault();setBusy(true);pedido.current ||=crypto.randomUUID();try{const {error}=await db.rpc('rh_banco_compensar',{p_funcionario:func,p_data:data,p_minutos:Math.round(Number(quantidade)*60),p_motivo:motivo,p_pedido:pedido.current});if(error)throw error;pedido.current=undefined;setQuantidade('');setMotivo('');toast.success('Folga registrada no banco');await carregar()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 const hoje=new Date().toLocaleDateString('en-CA');const saldo=creditos.filter(c=>!c.folha_id).reduce((s,c)=>s+c.minutos-c.compensados,0)
 return <div className="space-y-5"><h2 className="text-xl font-semibold">Banco de horas</h2><p>Configure prazo, jornada e percentuais em Configuração do RH → Banco de horas. As marcações completas geram créditos automaticamente após a configuração. Use Apurar ponto para conferir registros anteriores.</p><div className="flex flex-wrap gap-3"><label>Competência do ponto<Input type="month" value={mes} onChange={e=>setMes(e.target.value)}/></label><Button disabled={busy} onClick={()=>void apurar()}>Apurar ponto do mês</Button><label>Funcionário<select className="block border rounded p-2" value={func} onChange={e=>{setFunc(e.target.value);pedido.current=undefined}}><option value="">Selecione</option>{funcionarios.map(f=><option key={f.id} value={f.id}>{f.nome}</option>)}</select></label><Button variant="outline" onClick={()=>void carregar()}>Atualizar saldo</Button></div>
 {func&&<><p className="text-lg">Saldo não vinculado à folha: <strong>{horas(saldo)}</strong></p><form onSubmit={compensar} className="border rounded p-4 space-y-3"><h3 className="font-semibold">Registrar folga já realizada</h3><fieldset disabled={busy} className="grid sm:grid-cols-3 gap-3"><label>Data da folga<Input required type="date" max={hoje} value={data} onChange={e=>{setData(e.target.value);pedido.current=undefined}}/></label><label>Horas utilizadas<Input required type="number" min="0.02" max="744" step="0.01" value={quantidade} onChange={e=>{setQuantidade(e.target.value);pedido.current=undefined}}/></label><label>Motivo / descrição<Input required minLength={3} maxLength={500} value={motivo} onChange={e=>{setMotivo(e.target.value);pedido.current=undefined}}/></label><Button type="submit">Registrar compensação</Button></fieldset></form>
 <div className="overflow-auto"><table className="w-full text-sm"><thead><tr>{['Data do ponto','Crédito','Compensado','Restante','Vencimento','Adicional','Situação'].map(t=><th className="p-2 text-left" key={t}>{t}</th>)}</tr></thead><tbody>{creditos.map(c=><tr className="border-b" key={c.id}><td>{c.data}</td><td>{horas(c.minutos)}</td><td>{horas(c.compensados)}</td><td>{horas(c.minutos-c.compensados)}</td><td>{c.vence_em}</td><td>{c.percentual}%</td><td>{c.folha_id?`${c.folha?.status==='paga'?'Pago':'Na folha'} ${c.folha?.referencia}`:c.minutos===c.compensados?'Compensado':c.vence_em<=hoje?'Vencido — gerar folha':'Disponível'}</td></tr>)}</tbody></table></div><p className="text-sm">O saldo vencido entra como vencimento no holerite ao gerar a folha. O RH deve conferir os encargos antes de aprovar. Exibição limitada aos 500 créditos mais recentes.</p><h3 className="font-semibold">Histórico de folgas</h3>{folgas.map(f=><p key={f.id}>{f.data} · {horas(f.minutos)} · {f.motivo} · Operador: {f.operador}</p>)}</>}
 </div>
}
