'use client'
import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {toast} from 'sonner'
const dias=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado']
export function ConfiguracaoBancoHoras(){
 const [d,setD]=useState<any>(null),[versao,setVersao]=useState<string|null>(null),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false)
 async function carregar(){try{const r=await fetch('/api/rh/banco-horas');const b=await r.json();if(!r.ok)throw Error(b.error);setAdmin(b.isAdmin);setVersao(b.config?.updated_at||null);setD(b.config?.parametros||{inicio:new Date().toISOString().slice(0,10),prazo_meses:'',divisor:'',normal:'',sabado:'',domingo:'',feriado:'',jornada:[0,0,0,0,0,0,0],feriados:[]})}catch(e:any){toast.error(e.message)}}
 useEffect(()=>{void carregar()},[])
 async function salvar(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/rh/banco-horas',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({parametros:{...d,feriados:d.feriados.filter((v:string)=>v.trim()).map((v:string)=>v.trim())},versao})});const b=await r.json();if(!r.ok)throw Error(b.error);toast.success('Regras salvas. Confira e apure o ponto na aba Banco de horas.');await carregar()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 if(!d)return <p>Carregando banco de horas...</p>
 return <form onSubmit={salvar} className="space-y-4 max-w-4xl"><h2 className="text-xl font-semibold">Banco de horas e percentuais</h2><p>Preencha conforme a jornada e o acordo aplicáveis aos funcionários. As regras ficam registradas nos novos créditos. O saldo vencido entra na folha ao gerar a competência; não é registrado como pago até o pagamento da folha.</p><fieldset disabled={!admin||busy} className="space-y-4"><label>Apurar ponto a partir de<Input required type="date" value={d.inicio} onChange={e=>setD({...d,inicio:e.target.value})}/></label><div className="grid sm:grid-cols-3 gap-3">{[['prazo_meses','Vencimento em meses'],['divisor','Divisor mensal da hora'],['normal','Adicional em dias úteis (%)'],['sabado','Adicional sábado (%)'],['domingo','Adicional domingo (%)'],['feriado','Adicional feriado (%)']].map(([k,label])=><label key={k}>{label}<Input required type="number" min={k==='prazo_meses'||k==='divisor'?1:0} max={k==='prazo_meses'?36:k==='divisor'?744:500} step={k==='prazo_meses'?1:0.01} value={d[k]} onChange={e=>setD({...d,[k]:e.target.value===''?'':Number(e.target.value)})}/></label>)}</div><h3 className="font-semibold">Jornada diária (horas, sem intervalo)</h3><p>Jornada padrão desta instalação. Zero identifica um dia sem jornada prevista. Confira a escala antes de apurar.</p><div className="grid sm:grid-cols-4 gap-3">{dias.map((dia,i)=><label key={dia}>{dia}<Input required type="number" min={0} max={24} step="0.01" value={d.jornada[i]} onChange={e=>setD({...d,jornada:d.jornada.map((h:number,j:number)=>i===j?Number(e.target.value):h)})}/></label>)}</div><label className="block">Feriados (uma data por linha, AAAA-MM-DD)<textarea className="block border rounded w-full p-2" value={d.feriados.join('\n')} onChange={e=>setD({...d,feriados:e.target.value.split('\n')})}/></label><p>Valor a pagar = horas restantes × (salário / divisor) × (1 + adicional / 100). Informe 50 para um adicional de 50%, por exemplo.</p><Button disabled={busy} type="submit">Salvar banco de horas</Button></fieldset></form>
}
