import {calcularEncargos,ENCARGOS_2026,schemaEncargos} from '@/modules/rh/encargos'
import type {DetalhesHolerite} from '@/modules/rh/holerite'
const exemplo=(salario:number):DetalhesHolerite=>({codigo_funcionario:'1',sede:'',conta:'',admissao:'',dependentes:0,salario_contratual:salario,base_inss:null,base_irrf:null,base_fgts:null,rubricas:[{codigo:'001',campo:'salario_base',descricao:'Salário',referencia:'',valor:salario,incidencias:{inss:true,irrf:true,fgts:true}}]})
const calc=(s:number)=>calcularEncargos(exemplo(s),ENCARGOS_2026,'2026-09')
const desconto=(d:DetalhesHolerite,k:string)=>d.rubricas.find(r=>r.campo===k)!.valor
describe('Encargos mensais',()=>{
 test('salário de 2000: INSS progressivo, IRRF zero, FGTS não reduz o líquido',()=>{const d=calc(2000);expect(d.base_inss).toBe(2000);expect(d.base_fgts).toBe(2000);expect(d.base_irrf).toBe(1392.8);expect(desconto(d,'inss')).toBe(155.69);expect(desconto(d,'irrf')).toBe(0);expect(d.fgts_valor).toBe(160);expect(d.rubricas.some(r=>String(r.campo)==='fgts')).toBe(false)})
 test('INSS respeita teto e FGTS incide sem esse teto',()=>{expect(desconto(calc(10000),'inss')).toBe(desconto(calc(20000),'inss'));expect(calc(10000).base_inss).toBe(8475.55);expect(calc(10000).fgts_valor).toBe(800)})
 test('redução do IRRF usa rendimento tributável antes das deduções',()=>{const d=calc(6000);const sem=calcularEncargos(exemplo(6000),{...ENCARGOS_2026,reducao:{...ENCARGOS_2026.reducao,ativa:false}},'2026-09');expect(desconto(sem,'irrf')-desconto(d,'irrf')).toBeCloseTo(179.75,2);expect(desconto(calc(5000),'irrf')).toBe(0);expect(desconto(calc(7350),'irrf')).toBeGreaterThan(0)})
 test('deduções legais e dependentes podem superar simplificado',()=>{const d=calcularEncargos({...exemplo(6000),dependentes:3,outras_deducoes_irrf:400},ENCARGOS_2026,'2026-09');expect(d.base_irrf).toBeCloseTo(6000-desconto(d,'inss')-3*189.59-400,2)})
 test('incidências específicas e FGTS customizado',()=>{const e=exemplo(2000);e.fgts_aliquota=2;e.rubricas.push({campo:'outros_proventos',codigo:'2',descricao:'Verba sem incidência',referencia:'',valor:500,incidencias:{inss:false,irrf:false,fgts:false}},{campo:'faltas_desconto',codigo:'3',descricao:'Falta',referencia:'',valor:100,incidencias:{inss:true,irrf:true,fgts:true}});const d=calcularEncargos(e,ENCARGOS_2026,'2026-09');expect(d.base_inss).toBe(1900);expect(d.fgts_valor).toBe(38)})
 test('recalcular substitui encargos e não duplica rubricas',()=>{const d=calc(2000);const novo=calcularEncargos(d,ENCARGOS_2026,'2026-09');expect(novo.rubricas).toEqual(d.rubricas)})
 test('exige dependentes e incidência explícita para verba genérica',()=>{expect(()=>calcularEncargos({...exemplo(2000),dependentes:null},ENCARGOS_2026,'2026-09')).toThrow('dependentes');const e=exemplo(2000);e.rubricas[0].incidencias=undefined;expect(()=>calcularEncargos(e,ENCARGOS_2026,'2026-09')).toThrow('incidência')})
 test('bloqueia vigência errada, valores negativos e faixas invertidas',()=>{expect(()=>calcularEncargos(exemplo(2000),ENCARGOS_2026,'2025-09')).toThrow('Configure');expect(()=>calcularEncargos({...exemplo(2000),mes_irrf:'2027-01'},ENCARGOS_2026,'2026-12')).toThrow('Configure');expect(()=>calc(-1)).toThrow();expect(schemaEncargos.safeParse({...ENCARGOS_2026,inss:[{ate:2000,aliquota:9},{ate:1000,aliquota:12}]}).success).toBe(false)})
})
