import { sessionLock } from '@/lib/supabase/session-lock'
const original=Object.getOwnPropertyDescriptor(globalThis,'navigator')
afterEach(()=>{if(original)Object.defineProperty(globalThis,'navigator',original);else Reflect.deleteProperty(globalThis,'navigator');jest.useRealTimers()})
function locks(request:any){Object.defineProperty(globalThis,'navigator',{value:{locks:{request}},configurable:true})}
it('ignora refresh ocupado sem executar a renovação nem rejeitar',async()=>{const fn=jest.fn();const request=jest.fn((_n,_o,cb)=>Promise.resolve(cb(null)));locks(request);await expect(sessionLock('sessao',0,fn)).resolves.toBeUndefined();expect(fn).not.toHaveBeenCalled();expect(request.mock.calls[0][1]).toEqual({mode:'exclusive',ifAvailable:true})})
it('renova somente quando tem o bloqueio',async()=>{locks((_n:any,_o:any,cb:any)=>Promise.resolve(cb({name:'sessao'})));const fn=jest.fn(async()=>42);await expect(sessionLock('sessao',0,fn)).resolves.toBe(42);expect(fn).toHaveBeenCalledTimes(1)})
it('propaga falhas da operação, sem escondê-las como disputa de lock',async()=>{locks((_n:any,_o:any,cb:any)=>Promise.resolve().then(()=>cb({name:'sessao'})));await expect(sessionLock('sessao',1000,async()=>{throw Error('falha real')})).rejects.toThrow('falha real')})
it('cancela espera com prazo, sem executar operação desprotegida',async()=>{jest.useFakeTimers();locks((_n:any,o:any,_cb:any)=>new Promise((_r,reject)=>o.signal.addEventListener('abort',()=>reject(Error('aborted')))));const fn=jest.fn();const result=expect(sessionLock('sessao',100,fn)).rejects.toMatchObject({isAcquireTimeout:true});await jest.advanceTimersByTimeAsync(100);await result;expect(fn).not.toHaveBeenCalled()})
it('aguarda o lock exclusivo para operações normais',async()=>{let callback:any;let options:any;locks((_n:any,o:any,cb:any)=>{options=o;return new Promise(resolve=>{callback=()=>resolve(cb({name:'sessao'}))})});const fn=jest.fn(async()=>7);const result=sessionLock('sessao',-1,fn);expect(fn).not.toHaveBeenCalled();expect(options.ifAvailable).toBeUndefined();await callback();expect(await result).toBe(7)})
