FROM supabase/postgres:17.6.1.136
COPY upstream/docker/volumes/db/realtime.sql /docker-entrypoint-initdb.d/migrations/99-realtime.sql
COPY upstream/docker/volumes/db/webhooks.sql /docker-entrypoint-initdb.d/init-scripts/98-webhooks.sql
COPY upstream/docker/volumes/db/roles.sql /docker-entrypoint-initdb.d/init-scripts/99-roles.sql
COPY upstream/docker/volumes/db/jwt.sql /docker-entrypoint-initdb.d/init-scripts/99-jwt.sql
COPY upstream/docker/volumes/db/_supabase.sql /docker-entrypoint-initdb.d/migrations/97-_supabase.sql
COPY upstream/docker/volumes/db/logs.sql /docker-entrypoint-initdb.d/migrations/99-logs.sql
COPY upstream/docker/volumes/db/pooler.sql /docker-entrypoint-initdb.d/migrations/99-pooler.sql
