import {NextRequest} from 'next/server'
import {avisosAdmin,avisosAssociado} from '@/lib/avisos-servidor'
import {atorTema,ErroTema} from '@/lib/tema/servidor'
import {appDb,sessaoAssociado} from '@/lib/associado-app'
jest.mock('@/lib/tema/servidor',()=>{const r=jest.requireActual('@/lib/tema/servidor');return {...r,atorTema:jest.fn()}})
jest.mock('@/lib/associado-app',()=>({appDb:jest.fn(),sessaoAssociado:jest.fn(),limite:jest.fn()}))
const aid='9b1358a3-2b59-455f-ae08-6e2d7fc10ee4'
let q:any,db:any
const req=(path:string,method='GET',body?:any)=>new NextRequest('https://app.test'+path,{method,headers:{host:'app.test',origin:'https://app.test','content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})})
beforeEach(()=>{jest.clearAllMocks();q={};for(const k of ['select','eq','order','range','limit','or','in'])q[k]=jest.fn(()=>q);q.maybeSingle=jest.fn(async()=>({data:{id:aid,ativo:true,expira_em:null,publicado_em:null,imagem:Buffer.from('image').toString('base64')},error:null}));q.update=jest.fn(()=>q);q.upsert=jest.fn(async()=>({error:null}));q.then=(resolve:any)=>resolve({data:[],error:null});db={from:jest.fn(()=>q)};(appDb as jest.Mock).mockReturnValue(db);(atorTema as jest.Mock).mockResolvedValue({clube:'clube-a',user:{id:'admin-a'}});(sessaoAssociado as jest.Mock).mockResolvedValue({db,associado:{id:'socio-a',clube_id:'clube-a'}})})
it('rejeita gravação de outra origem antes de consultar a sessão',async()=>{const r=await avisosAdmin(new NextRequest('https://app.test/api/configuracoes/avisos',{method:'PATCH',headers:{host:'app.test',origin:'https://outro.test'}}));expect(r.status).toBe(403);expect(atorTema).not.toHaveBeenCalled()})
it('somente administrador ativo acessa o painel',async()=>{(atorTema as jest.Mock).mockRejectedValue(new ErroTema(403,'Sem permissão'));expect((await avisosAdmin(req('/api/configuracoes/avisos'))).status).toBe(403);expect(db.from).not.toHaveBeenCalled()})
it('associado sem sessão não consulta imagens ou avisos',async()=>{(sessaoAssociado as jest.Mock).mockResolvedValue(null);expect((await avisosAssociado(req('/api/associado-app/avisos?imagem='+aid))).status).toBe(401);expect(db.from).not.toHaveBeenCalled()})
it('imagem administrativa é filtrada pelo clube autenticado',async()=>{expect((await avisosAdmin(req('/api/configuracoes/avisos?imagem='+aid+'&clube_id=outro'))).status).toBe(200);expect(q.eq).toHaveBeenCalledWith('clube_id','clube-a')})
it('imagem pausada ou expirada não fica disponível ao associado',async()=>{q.maybeSingle.mockResolvedValueOnce({data:{ativo:false,expira_em:null},error:null});expect((await avisosAssociado(req('/api/associado-app/avisos?imagem='+aid))).status).toBe(404);q.maybeSingle.mockResolvedValueOnce({data:{ativo:true,expira_em:'2020-01-01'},error:null});expect((await avisosAssociado(req('/api/associado-app/avisos?imagem='+aid))).status).toBe(404)})
it('fechamento usa somente o associado da sessão e é idempotente',async()=>{expect((await avisosAssociado(req('/api/associado-app/avisos','POST',{id:aid}))).status).toBe(200);expect(q.eq).toHaveBeenCalledWith('clube_id','clube-a');expect(q.upsert).toHaveBeenCalledWith({aviso_id:aid,associado_id:'socio-a'},{onConflict:'aviso_id,associado_id',ignoreDuplicates:true})})
it('não permite marcar fechamento de outro associado',async()=>{expect((await avisosAssociado(req('/api/associado-app/avisos','POST',{id:aid,associado_id:'outro'}))).status).toBe(422);expect(q.upsert).not.toHaveBeenCalled()})
it('não publica aviso já vencido',async()=>{q.maybeSingle.mockResolvedValueOnce({data:{id:aid,expira_em:'2020-01-01'},error:null});expect((await avisosAdmin(req('/api/configuracoes/avisos','PATCH',{id:aid,acao:'publicar'}))).status).toBe(422);expect(q.update).not.toHaveBeenCalled()})
it('publicação exige aviso do mesmo clube',async()=>{q.maybeSingle.mockResolvedValueOnce({data:null,error:null});expect((await avisosAdmin(req('/api/configuracoes/avisos','PATCH',{id:aid,acao:'publicar'}))).status).toBe(404);expect(q.update).not.toHaveBeenCalled()})

it('grava tempo somente para o clube da sessão',async()=>{const {configurarTempoAvisos}=await import('@/lib/avisos-servidor');expect((await configurarTempoAvisos(req('/api/configuracoes/avisos/tempo','PUT',{tempo_segundos:60}))).status).toBe(200);expect(q.upsert).toHaveBeenCalledWith(expect.objectContaining({clube_id:'clube-a',tempo_segundos:60,atualizado_por:'admin-a'}),{onConflict:'clube_id'})})
it.each([-1,61,1.5,'30'])('rejeita tempo inválido %s',async tempo_segundos=>{const {configurarTempoAvisos}=await import('@/lib/avisos-servidor');expect((await configurarTempoAvisos(req('/api/configuracoes/avisos/tempo','PUT',{tempo_segundos}))).status).toBe(422);expect(q.upsert).not.toHaveBeenCalled()})
it('não permite cliente escolher o clube do tempo',async()=>{const {configurarTempoAvisos}=await import('@/lib/avisos-servidor');expect((await configurarTempoAvisos(req('/api/configuracoes/avisos/tempo','PUT',{tempo_segundos:30,clube_id:'outro'}))).status).toBe(422)})
it('associado recebe o tempo configurado para seu clube',async()=>{const config={select:jest.fn(()=>config),eq:jest.fn(()=>config),maybeSingle:jest.fn(async()=>({data:{tempo_segundos:15},error:null}))};db.from.mockImplementation((table:string)=>table==='clube_avisos_config'?config:q);const r=await avisosAssociado(req('/api/associado-app/avisos'));expect(r.status).toBe(200);expect((await r.json()).tempo_segundos).toBe(15);expect(config.eq).toHaveBeenCalledWith('clube_id','clube-a')})
