'use client'
import ConfiguracaoVersoCarteirinha from '@/components/ConfiguracaoVersoCarteirinha'
import ConfiguracaoFundoLogin from '@/components/ConfiguracaoFundoLogin'
import {useEffect,useRef,useState} from 'react'
import {useQueryClient} from '@tanstack/react-query'
import {Building2,Monitor,Tablet,Smartphone} from 'lucide-react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {Label} from '@/components/ui/label'
import {Card,CardHeader,CardTitle,CardDescription,CardContent} from '@/components/ui/card'
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from '@/components/ui/alert-dialog'
import {Cores,Tema,padrao,campos,coresSchema,avisos,sobre,MAX_ICONE,tiposIcone} from '@/lib/tema/modelo'
import {buscarTema,publicarTema} from '@/components/providers/tema-provider'
export default function ConfiguracaoPersonalizacao(){
 const [salvo,setSalvo]=useState<Tema|null>(null),[cores,setCores]=useState<Cores>({...padrao}),[file,setFile]=useState<File|null>(null),[acao,setAcao]=useState('manter'),[preview,setPreview]=useState(''),[validating,setValidating]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[erro,setErro]=useState(''),[sucesso,setSucesso]=useState(''),[tela,setTela]=useState<'desktop'|'tablet'|'celular'>('desktop');const lock=useRef(false),input=useRef<HTMLInputElement>(null),sequence=useRef(0),client=useQueryClient();
 async function carregar(){setLoading(true);setErro('');try{const tema=await buscarTema('/api/configuracoes/personalizacao');setSalvo(tema);setCores({...tema.cores});setFile(null);setAcao('manter');if(input.current)input.current.value=''}catch(e){setErro((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{carregar()},[]);
 useEffect(()=>{if(!file){setPreview('');return}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url)},[file]);
 async function selecionar(f?:File){const seq=++sequence.current;setErro('');setSucesso('');if(!f)return;setValidating(true);try{if(!tiposIcone.includes(f.type)||!f.size||f.size>MAX_ICONE)throw new Error('Use PNG, JPG ou WEBP de até 2 MB.');const bitmap=await createImageBitmap(f).catch(()=>{throw new Error('Não foi possível abrir a imagem. Selecione um PNG, JPG ou WEBP válido.')});const ok=bitmap.width>=192&&bitmap.height>=192&&bitmap.width<=4096&&bitmap.height<=4096;bitmap.close();if(!ok)throw new Error('A imagem deve ter entre 192 e 4096 pixels em cada dimensão.');if(seq===sequence.current){setFile(f);setAcao('substituir')}}catch(e){setErro((e as Error).message||'Não foi possível abrir a imagem.');if(input.current)input.current.value=''}finally{if(seq===sequence.current)setValidating(false)}}
 const valid=coresSchema.safeParse(cores),warnings=valid.success?avisos(valid.data):[],visual={...padrao,...Object.fromEntries(Object.entries(cores).filter(([,v])=>/^#[0-9a-f]{6}$/i.test(v)))} as Cores;
 async function salvar(){if(lock.current||validating||!salvo)return;setErro('');setSucesso('');if(!valid.success){setErro('Informe todas as cores no formato #RRGGBB.');return}if(warnings.length){setErro('Ajuste o contraste antes de salvar.');return}lock.current=true;setBusy(true);try{const body=new FormData();body.set('cores',JSON.stringify(valid.data));body.set('versao',String(salvo.versao));body.set('acao',acao);if(file&&acao==='substituir')body.set('icone',file);const tema=await buscarTema('/api/configuracoes/personalizacao',{method:'PUT',body});setSalvo(tema);setCores({...tema.cores});setFile(null);setAcao('manter');if(input.current)input.current.value='';client.setQueryData(['tema-aplicativo'],tema);publicarTema();setSucesso('Personalização salva e aplicada ao clube.')}catch(e){setErro((e as Error).message)}finally{lock.current=false;setBusy(false)}}
 const icon=preview||(acao==='manter'&&salvo?.icone?`/api/tema/icone?size=192&v=${salvo.versao}`:'/api/tema/icone?size=192&default=1');
 return <section aria-labelledby="personalizacao-titulo" className="space-y-6 min-w-0" aria-busy={loading||busy||validating}>
 <div><h2 id="personalizacao-titulo" className="text-2xl font-semibold">Personalização do Aplicativo</h2><p className="text-muted-foreground mt-2">Identidade visual deste clube no sistema e na área do associado. A prévia só será aplicada após salvar.</p></div>
 {erro&&<p role="alert" className="rounded-md border border-destructive p-3 text-destructive">{erro}</p>}{sucesso&&<p role="status" className="rounded-md border p-3">{sucesso}</p>}
 {validating&&<p role="status">Verificando imagem…</p>}{loading?<p role="status">Carregando personalização…</p>:!salvo?<Button onClick={carregar}>Tentar novamente</Button>:<>
 <div className="grid grid-cols-1 xl:grid-cols-2 gap-6 min-w-0">
 <div className="space-y-6 min-w-0"><ConfiguracaoVersoCarteirinha/><ConfiguracaoFundoLogin/><Card><CardHeader><CardTitle>Ícone do aplicativo</CardTitle><CardDescription>PNG, JPG, JPEG ou WEBP. Até 2 MB, de 192 a 4096 pixels em cada dimensão. O ícone será ajustado a um quadrado, sem cortar a imagem.</CardDescription></CardHeader><CardContent className="space-y-4">
 <div className="flex flex-wrap gap-4 items-center"><div className="w-20 h-20 rounded-2xl border bg-white grid place-items-center overflow-hidden">{icon?<img src={icon} alt="Prévia do ícone do aplicativo" className="w-full h-full object-contain"/>:<Building2 className="h-10 w-10" aria-label="Ícone padrão do sistema"/>}</div><p className="text-sm">{acao==='remover'?'O ícone padrão será restaurado ao salvar.':file?file.name:salvo.icone?'Ícone personalizado atual':'Ícone padrão do sistema'}</p></div>
 <Label htmlFor="tema-icone">Enviar ou substituir o ícone</Label><Input id="tema-icone" type="file" ref={input} accept="image/png,image/jpeg,image/webp,.png,.jpg,.jpeg,.webp" disabled={busy||validating} onChange={e=>selecionar(e.target.files?.[0])}/>
 <Button variant="outline" disabled={busy||validating||(!file&&!salvo.icone)} onClick={()=>{sequence.current++;setFile(null);setAcao('remover');if(input.current)input.current.value=''}}>Remover ícone</Button>
 </CardContent></Card>
 <Card><CardHeader><CardTitle>Cores do clube</CardTitle><CardDescription>Use seis dígitos após #. Textos de cabeçalhos e botões recebem contraste automático.</CardDescription></CardHeader><CardContent className="grid grid-cols-1 sm:grid-cols-2 gap-5">
 {(Object.keys(campos) as (keyof Cores)[]).map(k=><div key={k} className="min-w-0 space-y-2"><Label htmlFor={`hex-${k}`}>{campos[k]}</Label><div className="flex gap-2 min-w-0"><input aria-label={`Selecionar ${campos[k].toLowerCase()}`} type="color" value={visual[k]} onChange={e=>setCores(c=>({...c,[k]:e.target.value.toUpperCase()}))} disabled={busy||validating} className="w-12 h-11 shrink-0 rounded border cursor-pointer focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2"/><Input id={`hex-${k}`} value={cores[k]} disabled={busy||validating} maxLength={7} spellCheck={false} autoComplete="off" onChange={e=>setCores(c=>({...c,[k]:e.target.value.toUpperCase()}))} aria-invalid={!/^#[0-9A-F]{6}$/i.test(cores[k])} aria-describedby={!/^#[0-9A-F]{6}$/i.test(cores[k])?`erro-${k}`:undefined}/></div>{!/^#[0-9A-F]{6}$/i.test(cores[k])&&<p id={`erro-${k}`} className="text-sm text-destructive">Use #RRGGBB, por exemplo #103F35.</p>}</div>)}
 </CardContent></Card></div>
 <div className="min-w-0"><Card><CardHeader><CardTitle>Pré-visualização</CardTitle><CardDescription>Exemplo visual com dados fictícios.</CardDescription></CardHeader><CardContent className="space-y-4 min-w-0"><div role="group" aria-label="Tamanho da prévia" className="flex flex-wrap gap-2">{([['desktop','Computador',Monitor],['tablet','Tablet',Tablet],['celular','Celular',Smartphone]] as const).map(([id,label,Icon])=><Button key={id} variant={tela===id?'default':'outline'} aria-pressed={tela===id} onClick={()=>setTela(id)}><Icon className="h-4 w-4 mr-2"/>{label}</Button>)}</div>
 <div data-testid="tema-preview" className="border rounded-2xl overflow-hidden mx-auto w-full" style={{maxWidth:tela==='celular'?320:tela==='tablet'?440:640,background:visual.fundo,color:visual.texto}}>
 <div className="p-4 flex gap-3 items-center" style={{background:visual.cabecalho,color:sobre(visual.cabecalho)}}>{icon?<img src={icon} alt="Ícone na prévia" className="w-9 h-9 object-contain"/>:<Building2 className="w-8 h-8"/>}<strong>Seu clube</strong></div>
 <div className={tela==='celular'?'flex flex-col':'flex'}><div className={`${tela==='celular'?'w-full':'w-28 shrink-0'} p-3 text-sm space-y-3`} style={{background:visual.menu,color:visual.textoMenu}}><p>Início</p><p>Associados</p><p>Mensagens</p></div><div className="p-4 min-w-0 space-y-4 flex-1"><h3 className="font-semibold text-lg">Bem-vindo ao clube</h3><p className="text-sm">Sua carteirinha e informações em um só lugar.</p><div className="p-3 rounded-xl text-sm" style={{background:visual.secundaria,color:sobre(visual.secundaria)}}>Mensalidade em dia</div><span className="inline-block rounded-full px-3 py-1 text-xs" style={{background:visual.destaque,color:sobre(visual.destaque)}}>Novidade</span><div><span className="inline-block underline" style={{color:visual.primaria}}>Ver informações</span></div><span className="inline-flex rounded-lg p-3 text-sm font-medium" style={{background:visual.botoes,color:sobre(visual.botoes)}}>Acessar carteirinha</span></div></div></div>
 <div aria-live="polite">{warnings.length>0?<div className="border border-destructive rounded-md p-3"><p className="font-semibold">Contraste insuficiente</p><ul className="list-disc pl-5 text-sm">{warnings.map(w=><li key={w}>{w}</li>)}</ul><p className="text-sm mt-2">Ajuste as cores para salvar com contraste WCAG AA.</p></div>:valid.success?<p className="text-sm text-muted-foreground">Combinações de texto verificadas: contraste mínimo de 4,5:1.</p>:null}</div>
 </CardContent></Card></div></div>
 <div className="flex flex-wrap gap-3"><Button disabled={busy||validating||!valid.success||warnings.length>0} onClick={salvar}>{busy?'Salvando…':'Salvar alterações'}</Button><Button variant="outline" disabled={busy||validating} onClick={()=>{setSucesso('');carregar()}}>Cancelar</Button>
 <AlertDialog><AlertDialogTrigger asChild><Button variant="outline" disabled={busy||validating}>Restaurar cores padrão</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Restaurar cores padrão?</AlertDialogTitle><AlertDialogDescription>As nove cores da prévia voltarão ao padrão do sistema. O ícone será mantido. Clique em Salvar alterações para aplicar.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Manter cores</AlertDialogCancel><AlertDialogAction onClick={()=>{setCores({...padrao});setSucesso('Cores padrão na prévia. Salve para aplicar.');setErro('')}}>Restaurar cores</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div></>}
 </section>
}
