'use client'
import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {toast} from 'sonner'
import {mensagemLicenca} from '@/lib/licenca'
async function resposta(r:Response){const d=await r.json();if(!r.ok)throw Error(d.error||'Não foi possível consultar a licença');return d}
export function AcoesLicenca({atualizar}:{atualizar:()=>void}){const [busy,setBusy]=useState(false);async function acao(acao:string){setBusy(true);try{const d=await resposta(await fetch('/api/sistema/licenca',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({acao})}));if(d.url){const url=new URL(d.url);if(url.protocol!=='https:')throw Error('URL de cobrança inválida');window.location.assign(url.href)}else{toast.success(d.renovada?'Licença renovada.':d.mensagem||'Consulta concluída. A validade foi atualizada quando houve pagamento confirmado.');atualizar();window.dispatchEvent(new Event('licenca-atualizada'))}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}return <div className="flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>void acao('renovar')}>Renovar agora</Button><Button variant="outline" disabled={busy} onClick={()=>void acao('assinatura')}>Ver dados da assinatura</Button><Button variant="outline" disabled={busy} onClick={()=>void acao('verificar')}>Verificar pagamento</Button></div>}
export function LicencaPainel(){const [dados,setDados]=useState<any>(null),[fechado,setFechado]=useState(''),[erro,setErro]=useState(false)
 useEffect(()=>{let ativo=true;async function carregar(){try{const d=await resposta(await fetch('/api/sistema/licenca'));if(!ativo)return;setDados(d);setErro(false);try{setFechado(sessionStorage.getItem('licenca-aviso-fechado')||'')}catch{setFechado('')}}catch{if(ativo)setErro(true)}}void carregar();const t=setInterval(()=>void carregar(),60000);window.addEventListener('focus',carregar);window.addEventListener('licenca-atualizada',carregar);return()=>{ativo=false;clearInterval(t);window.removeEventListener('focus',carregar);window.removeEventListener('licenca-atualizada',carregar)}},[])
 const atualizar=()=>window.dispatchEvent(new Event('licenca-atualizada'))
 if(erro)return <div className="px-4 py-2 text-sm bg-amber-50">Não foi possível atualizar a licença. <a href="/dashboard/configuracoes?licenca=configurar" className="underline">Ver configuração</a></div>
 if(!dados?.licenca)return null
 const l=dados.licenca;return <section className="border-b bg-white px-4 py-2" aria-label="Licença do sistema"><div className="flex flex-wrap gap-x-4 gap-y-1 text-sm"><strong className={dados.status==='VENCENDO'?'text-amber-700':dados.status==='VENCIDA'?'text-red-700':'text-slate-700'}>{dados.status}</strong><span>Licença válida até: {l.data_vencimento?l.data_vencimento.split('-').reverse().join('/'):'Aguardando pagamento'}</span>{dados.dias!==null&&<span>{dados.dias<0?'Vencida há:':'Restam:'} {Math.abs(dados.dias)} dias</span>}</div>
 {dados.aviso&&dados.aviso.id!==fechado&&<div role="alert" className="mt-3 rounded border border-amber-300 bg-amber-50 p-4 space-y-3"><p className="whitespace-pre-line">{mensagemLicenca(l.data_vencimento,dados.dias)}</p><AcoesLicenca atualizar={atualizar}/><Button variant="ghost" onClick={()=>{try{sessionStorage.setItem('licenca-aviso-fechado',dados.aviso.id)}catch{}setFechado(dados.aviso.id)}}>Fechar aviso</Button></div>}</section>
}
export function ConfiguracaoLicenca(){const [c,setC]=useState<any>(null),[integracao,setIntegracao]=useState<any>(null),[dias,setDias]=useState(''),[erro,setErro]=useState(''),[busy,setBusy]=useState(false)
 async function carregar(){try{setErro('');const [d,i]=await Promise.all([fetch('/api/sistema/licenca').then(resposta),fetch('/api/sistema/licenca/integracoes').then(resposta)]);setC(d);setDias(d.config.antecedencias.join(', '));setIntegracao({...i,stripe_secret:'',stripe_webhook:'',resend_key:''})}catch(e:any){setErro(e.message)}}
 useEffect(()=>{void carregar()},[])
 async function salvarAvisos(e:React.FormEvent){e.preventDefault();setBusy(true);try{await resposta(await fetch('/api/sistema/licenca',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({antecedencias:dias.split(',').map(v=>v.trim()===''?NaN:Number(v.trim())),interno:c.config.interno,versao:c.config.atualizado_em})}));toast.success('Antecedência salva');await carregar();window.dispatchEvent(new Event('licenca-atualizada'))}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function salvarIntegracao(e:React.FormEvent){e.preventDefault();setBusy(true);try{await resposta(await fetch('/api/sistema/licenca/integracoes',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...integracao,versao:integracao.atualizado_em})}));toast.success('Integração salva');await carregar()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 if(erro)return <p role="alert">{erro} <Button onClick={()=>void carregar()}>Tentar novamente</Button></p>
 if(!c||!integracao)return <p>Carregando licença...</p>
 const mudar=(k:string,v:unknown)=>setIntegracao({...integracao,[k]:v})
 return <div className="space-y-6 max-w-4xl"><h2 className="text-xl font-semibold">Licença e assinatura</h2><p>{c.licenca?`${c.licenca.empresa} · ${c.licenca.id}`:'Nenhuma licença vinculada. Configure o Stripe e inicie a assinatura.'}</p><AcoesLicenca atualizar={()=>void carregar()}/>
 <form onSubmit={salvarAvisos} className="border rounded p-4 space-y-3"><h3 className="font-semibold">Avisos de vencimento</h3><label>Dias de antecedência, separados por vírgula<Input required value={dias} onChange={e=>setDias(e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={c.config.interno} onChange={e=>setC({...c,config:{...c.config,interno:e.target.checked}})}/>Aviso interno no painel administrativo</label><p className="text-sm">Padrão: 15, 7, 3, 1 e 0. Zero significa o dia do vencimento. O status VENCENDO aparece nos últimos 15 dias. Os avisos não bloqueiam o uso do sistema.</p><Button disabled={busy}>Salvar avisos</Button></form>
 <form onSubmit={salvarIntegracao} className="border rounded p-4 space-y-4"><h3 className="font-semibold">Stripe</h3><fieldset disabled={busy} className="space-y-4"><div className="grid sm:grid-cols-2 gap-3">{([['empresa','Empresa'],['app_url','Endereço do sistema'],['stripe_price','ID do preço recorrente (price_...)']] as const).map(([k,l])=><label key={k}>{l}<Input required value={integracao[k]} onChange={e=>mudar(k,e.target.value)}/></label>)}{([['stripe_secret','Chave secreta Stripe','stripe_configurado'],['stripe_webhook','Segredo do webhook','webhook_configurado']] as const).map(([k,l,flag])=><label key={k}>{l}<Input type="password" autoComplete="new-password" value={integracao[k]} onChange={e=>mudar(k,e.target.value)} placeholder={integracao[flag]?'Salvo — em branco para manter':'Não configurado'}/></label>)}</div>
 <p className="text-sm">No Stripe, configure um produto com preço recorrente e habilite o portal do cliente. Endpoint do webhook: <code className="break-all">{integracao.app_url.replace(/\/$/,'')}/api/webhooks/stripe-licenca</code>. Eventos: invoice.paid, checkout.session.completed e checkout.session.async_payment_succeeded. Em localhost, encaminhe os eventos com Stripe CLI.</p>
 <h3 className="font-semibold">Canais opcionais</h3><label className="flex gap-2"><input type="checkbox" checked={integracao.email_ativo} onChange={e=>mudar('email_ativo',e.target.checked)}/>Enviar e-mail pelo Resend</label>{integracao.email_ativo&&<div className="grid sm:grid-cols-2 gap-3"><label>Remetente verificado<Input type="email" required value={integracao.email_remetente} onChange={e=>mudar('email_remetente',e.target.value)}/></label><label>E-mail do cliente<Input type="email" required value={integracao.email_destino} onChange={e=>mudar('email_destino',e.target.value)}/></label><label>Chave do Resend<Input type="password" autoComplete="new-password" value={integracao.resend_key} onChange={e=>mudar('resend_key',e.target.value)} placeholder={integracao.email_configurado?'Salva — em branco para manter':'Não configurada'}/></label></div>}
 <label className="flex gap-2"><input type="checkbox" checked={integracao.whatsapp_ativo} onChange={e=>mudar('whatsapp_ativo',e.target.checked)}/>Enviar WhatsApp ao cliente</label>{integracao.whatsapp_ativo&&<div className="grid sm:grid-cols-2 gap-3"><label>Provedor<select className="block border rounded p-2 w-full" required value={integracao.whatsapp_provider||''} onChange={e=>mudar('whatsapp_provider',e.target.value||null)}><option value="">Selecione</option>{integracao.providers.map((p:any)=><option key={p.id} value={p.id}>{p.nome} · {p.tipo}</option>)}</select></label><label>Telefone com código do país<Input required placeholder="5511999999999" value={integracao.whatsapp_destino} onChange={e=>mudar('whatsapp_destino',e.target.value)}/></label><label>Template aprovado na Meta<Input value={integracao.whatsapp_template} onChange={e=>mudar('whatsapp_template',e.target.value)}/></label><p className="text-sm">Na Meta, use um template pt_BR com dois parâmetros no corpo: dias restantes e data de vencimento. O WaSender utiliza a mensagem de texto.</p></div>}
 <Button disabled={busy}>Salvar integração</Button></fieldset></form></div>
}
