'use client'
import {useEffect,useState} from 'react'
import {Button} from '@/components/ui/button'
import {Input} from '@/components/ui/input'
import {toast} from 'sonner'
const prioridades=[['critica','Crítica'],['alta','Alta'],['normal','Normal'],['baixa','Baixa']]
export default function SuporteTelefone({editar=false}:{editar?:boolean}){
 const [d,setD]=useState<any>(null),[versao,setVersao]=useState<string|null>(null),[loading,setLoading]=useState(true),[admin,setAdmin]=useState(false),[busy,setBusy]=useState(false),[erro,setErro]=useState('')
 async function carregar(){setErro('');try{const r=await fetch('/api/suporte');const b=await r.json();if(!r.ok)throw Error(b.error);setAdmin(b.admin);setVersao(b.versao);setD(b.config||(editar?{nome:'',telefone:'',horario:'',contagem:'horas_uteis',observacoes:'',prazos:prioridades.map(([prioridade])=>({prioridade,resposta:'',solucao:''}))}:null))}catch(e:any){setErro(e.message)}finally{setLoading(false)}}
 useEffect(()=>{void carregar()},[editar])
 async function salvar(e:React.FormEvent){e.preventDefault();setBusy(true);try{const r=await fetch('/api/suporte',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:d,versao})});const b=await r.json();if(!r.ok)throw Error(b.error);toast.success('Telefone e SLA publicados na página Suporte');await carregar()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 if(loading)return <p>Carregando suporte...</p>
 if(erro)return <p role="alert">{erro} <Button variant="outline" onClick={()=>void carregar()}>Tentar novamente</Button></p>
 if(!editar&&!d)return <div className="border rounded bg-white p-6"><h1 className="text-2xl font-semibold">Suporte por telefone</h1><p>O responsável pelo sistema ainda não cadastrou o telefone e as condições de atendimento.</p></div>
 if(editar&&!admin)return <p>Somente o administrador pode editar as informações de suporte.</p>
 const tabela=<table className="w-full text-sm"><thead><tr><th className="text-left p-2">Prioridade</th><th className="text-left p-2">Primeira resposta (horas)</th><th className="text-left p-2">Solução (horas)</th></tr></thead><tbody>{d.prazos.map((p:any,i:number)=><tr className="border-t" key={p.prioridade}><td className="p-2">{prioridades.find(([k])=>k===p.prioridade)?.[1]}</td>{['resposta','solucao'].map(k=><td className="p-2" key={k}>{editar?<Input aria-label={k+' '+p.prioridade} required type="number" min="0.01" max="8760" step="0.01" value={p[k]} onChange={e=>setD({...d,prazos:d.prazos.map((r:any,j:number)=>i===j?{...r,[k]:e.target.value===''?'':Number(e.target.value)}:r)})}/>:p[k]}</td>)}</tr>)}</tbody></table>
 if(!editar)return <section className="bg-white border rounded p-6 space-y-5"><h1 className="text-2xl font-bold">Suporte do sistema</h1><h2 className="text-lg font-semibold">{d.nome}</h2><a className="inline-block bg-blue-600 text-white px-5 py-3 rounded" href={'tel:'+d.telefone.replace(/[^+\d]/g,'')}>Ligar: {d.telefone}</a><div><h3 className="font-semibold">Horário de atendimento</h3><p className="whitespace-pre-wrap">{d.horario}</p></div><h3 className="font-semibold">Prazos de atendimento (SLA)</h3><p>Contagem em {d.contagem==='horas_uteis'?'horas úteis, dentro do horário de atendimento informado':'horas corridas'}.</p><div className="overflow-auto">{tabela}</div><p className="whitespace-pre-wrap">{d.observacoes}</p><p className="text-sm text-slate-600">Entre em contato por telefone. Esta página informa as condições do suporte; não abre chamado nem inicia uma contagem automática.</p></section>
 return <form className="max-w-4xl space-y-4" onSubmit={salvar}><h2 className="text-xl font-semibold">Suporte por telefone e SLA</h2><p>Cadastre os contatos e os prazos oferecidos à empresa cliente. As informações aparecerão no menu Suporte.</p><fieldset disabled={busy} className="space-y-4">{[['nome','Nome do suporte / empresa'],['telefone','Telefone com DDD']].map(([k,label])=><label className="block" key={k}>{label}<Input required maxLength={k==='nome'?120:40} value={d[k]} onChange={e=>setD({...d,[k]:e.target.value})}/></label>)}<label className="block">Dias, horários e fuso do atendimento<textarea required maxLength={300} className="border rounded p-2 block w-full" placeholder="Informe dias, horários, fuso e atendimento em feriados" value={d.horario} onChange={e=>setD({...d,horario:e.target.value})}/></label><label className="block">Contagem dos prazos<select className="block border rounded p-2" value={d.contagem} onChange={e=>setD({...d,contagem:e.target.value})}><option value="horas_uteis">Horas úteis</option><option value="horas_corridas">Horas corridas</option></select></label><div className="overflow-auto">{tabela}</div><label className="block">Condições e orientações<textarea maxLength={2000} className="block w-full border rounded p-2" value={d.observacoes} onChange={e=>setD({...d,observacoes:e.target.value})}/></label><Button type="submit" disabled={busy}>{busy?'Salvando...':'Salvar e publicar suporte'}</Button></fieldset></form>
}
