import {detalhesHolerite,ehVencimento} from './holerite'
import type {FolhaPagamento} from './types'
import {escapeHtml} from '@/lib/security'
import {dataDocumento} from '@/lib/impressao-documento'
const moeda=(v:number)=>Number(v??0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})
const esc=(v:unknown)=>escapeHtml(String(v??''))
const labels:Record<string,string>={rascunho:'Rascunho',calculada:'Calculada',aprovada:'Aprovada',paga:'Paga',cancelada:'Cancelada'}
const proventos=[['salario_base','Salário base'],['horas_extras_valor','Horas extras'],['adicional_noturno','Adicional noturno'],['adicional_insalubridade','Insalubridade'],['adicional_periculosidade','Periculosidade'],['gratificacao','Gratificação'],['comissao','Comissão'],['outros_proventos','Outros proventos']] as const
const descontos=[['inss','INSS'],['irrf','IRRF'],['vale_transporte','Vale-transporte'],['vale_refeicao','Vale-refeição'],['faltas_desconto','Faltas'],['atrasos_desconto','Atrasos'],['adiantamento','Adiantamento'],['outros_descontos','Outros descontos']] as const
export function conteudoFolha(folhas:FolhaPagamento[],empresa:{empresa_nome:string;empresa_documento:string},referencia:string,individual=false,filtro='Todos'){
 const cabecalho=`<h1>${individual?'Demonstrativo de pagamento':'Folha de pagamento'}</h1><p><strong>${esc(empresa.empresa_nome||'Empresa não configurada')}</strong> · ${esc(empresa.empresa_documento)}</p><p>Competência: ${esc(referencia)}${individual?'':' · Status: '+esc(filtro)}</p>`
 const css='<style>table{width:100%;border-collapse:collapse;font-size:10pt}th,td{border:1px solid #aaa;padding:7px;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}.valor{text-align:right;white-space:nowrap}.nota{font-size:9pt}.assinatura{margin-top:25mm;border-top:1px solid;padding-top:6px}</style>'
 if(individual){
  const f=folhas[0];if(!f)throw Error('Folha não encontrada.');const d=detalhesHolerite(f)
  const dado=(v:unknown)=>v==null||v===''?'Não informado':esc(v)
  const base=(v:number|null)=>v==null?'Não informado':moeda(v)
  const identificacao=(titulo:string,valor:unknown)=>`<div><small>${titulo}</small><br><strong>${dado(valor)}</strong></div>`
  return css+`<style>.holerite{font-size:9pt}.holerite h1{font-size:14pt;margin:0}.holerite .empresa{display:flex;justify-content:space-between;border:1px solid #333;padding:10px;gap:12px}.holerite .identificacao{display:grid;grid-template-columns:1fr 3fr 2fr;gap:10px;border:1px solid #333;border-top:0;padding:10px;margin-bottom:14px}.holerite th{background:#24418f;color:white;print-color-adjust:exact;-webkit-print-color-adjust:exact}.holerite td,.holerite th{padding:5px;font-size:9pt}.holerite .bases th{background:white;color:#111;font-weight:normal;font-size:8pt}.holerite .obs{white-space:pre-wrap;max-width:90mm}.holerite .assinatura{margin-top:14mm}.holerite small{font-size:8pt}</style>
  <section class="holerite"><header class="empresa"><div><strong>${esc(empresa.empresa_nome||'Empresa não configurada')}</strong><p>CNPJ / CPF: ${dado(empresa.empresa_documento)}</p></div><div><h1>Demonstrativo de pagamento</h1><p>Competência: ${esc(referencia.split('-').reverse().join('/'))}</p><small>Status: ${esc(labels[f.status]||f.status)}</small></div></header>
  <div class="identificacao">${identificacao('Código',d.codigo_funcionario)}${identificacao('Nome do funcionário',f.funcionario?.nome)}${identificacao('Departamento',f.funcionario?.departamento)}${identificacao('Sede / unidade',d.sede)}${identificacao('Cargo',f.funcionario?.cargo)}${identificacao('Admissão',d.admissao?dataDocumento(d.admissao):'')}${identificacao('Salário base',base(d.salario_contratual))}${identificacao('Conta para depósito',d.conta)}${identificacao('Data de pagamento',f.data_pagamento?dataDocumento(f.data_pagamento):'Não registrado')}</div>
  <table><thead><tr><th>Código</th><th>Descrição</th><th>Referência</th><th>Vencimentos</th><th>Descontos</th></tr></thead><tbody>${d.rubricas.map(r=>`<tr><td>${dado(r.codigo)}</td><td>${esc(r.descricao)}</td><td>${dado(r.referencia)}</td><td class="valor">${ehVencimento(r)?moeda(r.valor):''}</td><td class="valor">${ehVencimento(r)?'':moeda(r.valor)}</td></tr>`).join('')}${d.rubricas.length<8?'<tr style="height:65mm"><td></td><td></td><td></td><td></td><td></td></tr>':''}
  <tr><td colspan="3" rowspan="3" class="obs"><strong>OBSERVAÇÕES</strong><br>${esc(f.observacao)}</td><th>Total de vencimentos</th><th>Total de descontos</th></tr><tr><td class="valor">${moeda(f.total_proventos)}</td><td class="valor">${moeda(f.total_descontos)}</td></tr><tr><td><strong>Valor líquido</strong></td><td class="valor"><strong>${moeda(f.salario_liquido)}</strong></td></tr></tbody></table>
  <table class="bases"><thead><tr><th>Salário base</th><th>Base INSS</th><th>Base IRRF</th><th>Base FGTS</th><th>Dependentes</th><th>Conta (depósito)</th></tr></thead><tbody><tr><td>${base(d.salario_contratual)}</td><td>${base(d.base_inss)}</td><td>${base(d.base_irrf)}</td><td>${base(d.base_fgts)}</td><td>${dado(d.dependentes)}</td><td>${dado(d.conta)}</td></tr></tbody></table>
  <p class="nota">Valores registrados no sistema. Este demonstrativo não confirma o pagamento.</p><p class="assinatura">Assinatura do funcionário · Data: ____/____/________</p></section>`
 }

 const total=(campo:'total_proventos'|'total_descontos'|'salario_liquido')=>moeda(folhas.reduce((s,f)=>s+Number(f[campo]??0),0))
 return css+cabecalho+`<table><thead><tr><th>Funcionário / cargo</th><th>Status</th><th>Proventos</th><th>Descontos</th><th>Líquido</th></tr></thead><tbody>${folhas.map(f=>`<tr><td>${esc(f.funcionario?.nome||'Não informado')}<br>${esc(f.funcionario?.cargo)}</td><td>${esc(labels[f.status]||f.status)}</td><td class="valor">${moeda(f.total_proventos)}</td><td class="valor">${moeda(f.total_descontos)}</td><td class="valor">${moeda(f.salario_liquido)}</td></tr>`).join('')}</tbody></table><p><strong>Total (${folhas.length} folhas):</strong> Proventos ${total('total_proventos')} · Descontos ${total('total_descontos')} · Líquido ${total('salario_liquido')}</p><p class="nota">Totais dos registros selecionados, incluindo rascunhos ou cancelados quando presentes no filtro. A impressão não altera o status nem registra pagamento.</p>`
}
